version: '3.4'

services:
  shoppinglistbackend:
    image: shoppinglistbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      MONGO_DB_CONNECTION_STRING: mongodb://tutorial:tutorial@mongo:27017/tutorial
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
    volumes:
      - ./:/usr/src/app
